### ISSUE TITLE
Разместить в проектном вики сценарии для навыка Алисы

### ISSUE THREAD

**Issue by vkamiansky** [vkamiansky/hackathonfls2019#19]
Перенести наработки по бизнес-анализу (в формате базовой функциональности первой версии) в Вики проекта.

**Comment by maxPakin** [comment]
Вики проекта - это где?

**Comment by vkamiansky** [comment]
https://github.com/vkamiansky/hackathonfls2019/wiki

**Comment by vkamiansky** [comment]
Там есть и свой репозиторий, в котором можно хранить картинки и прочие информационные файлы для скачивания.

**Comment by maxPakin** [comment]
@vkamiansky На английском? Для русского ассистента, кажется, это будет излишним

**Comment by vkamiansky** [comment]
@maxPakin лучше на русском.

**Comment by vkamiansky** [comment]
готово
