### ISSUE TITLE
Добавить новое значение "SayIllegalArgument" в InputProcessingCommand

### ISSUE THREAD

**Issue by MartenMink** [vkamiansky/hackathonfls2019#38]
Добавить новое значение "SayIllegalArgument", которое будет отвечать за неверные аргументы в известных командах, например: "Добавь яблоки -2 штуки" или "Удали молоко 1 котик".
Аргументы - количество или единицы измерения.

**Comment by vkamiansky** [comment]
Не совсем понятно, как для пользователя это будет отличаться от ситуации нераспознанной команды. Есть идеи?
